{"timestamp":"2025-08-04T15:31:34.988011","level":"info","event":"DAG bundles loaded: dags-folder, example_dags","logger":"airflow.dag_processing.bundles.manager.DagBundlesManager"}
{"timestamp":"2025-08-04T15:31:34.988472","level":"info","event":"Filling up the DagBag from /opt/airflow/dags/extract_dag.py","logger":"airflow.models.dagbag.DagBag"}
{"timestamp":"2025-08-04T15:31:35.010255Z","level":"info","event":"Task instance is in running state","chan":"stdout","logger":"task"}
{"timestamp":"2025-08-04T15:31:35.010681Z","level":"info","event":" Previous state of the Task instance: TaskInstanceState.QUEUED","chan":"stdout","logger":"task"}
{"timestamp":"2025-08-04T15:31:35.012663Z","level":"info","event":"Current task name:load_data","chan":"stdout","logger":"task"}
{"timestamp":"2025-08-04T15:31:35.012784Z","level":"info","event":"Dag name:extract_load_data","chan":"stdout","logger":"task"}
{"timestamp":"2025-08-04T15:31:35.019361","level":"info","event":"Connection Retrieved 'med_postgres'","logger":"airflow.hooks.base"}
{"timestamp":"2025-08-04T15:31:43.040881","level":"error","event":"Task failed with exception","logger":"task","error_detail":[{"exc_type":"OperationalError","exc_value":"could not translate host name \"host.docker.local\" to address: Temporary failure in name resolution\n","exc_notes":[],"syntax_error":null,"is_cause":false,"frames":[{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py","lineno":877,"name":"run"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py","lineno":1164,"name":"_execute_task"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/bases/operator.py","lineno":397,"name":"wrapper"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/operators/python.py","lineno":217,"name":"execute"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/operators/python.py","lineno":240,"name":"execute_callable"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/callback_runner.py","lineno":81,"name":"run"},{"filename":"/opt/airflow/dags/extract_dag.py","lineno":47,"name":"load_data"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/psycopg2/__init__.py","lineno":122,"name":"connect"}],"is_group":false,"exceptions":[]}]}
{"timestamp":"2025-08-04T15:31:43.047559Z","level":"info","event":"Task instance in failure state","chan":"stdout","logger":"task"}
{"timestamp":"2025-08-04T15:31:43.049253Z","level":"info","event":"Task start","chan":"stdout","logger":"task"}
{"timestamp":"2025-08-04T15:31:43.049495Z","level":"info","event":"Task:<Task(PythonOperator): load_data>","chan":"stdout","logger":"task"}
{"timestamp":"2025-08-04T15:31:43.049663Z","level":"info","event":"Failure caused by could not translate host name \"host.docker.local\" to address: Temporary failure in name resolution","chan":"stdout","logger":"task"}
{"timestamp":"2025-08-04T15:31:43.049827Z","level":"info","event":"","chan":"stdout","logger":"task"}
